# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-02 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mainshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainshow',
            name='categoryid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname3',
            field=models.CharField(max_length=50),
        ),
    ]
